version: '3.8'

services:
  api:
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./dockerfile
      target: dev
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
      - 9229:9229
    volumes:
      - ./src:/home/node/app/src
      - ./test:/home/node/app/test
      - ./node_modules:/home/node/app/node_modules