version: '3.8'

services:
  api:
    container_name: ${DOCKER_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${NODE_PORT}:${NODE_PORT}